[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["rc"] }
serde_derive = "1.0.204"
chrono = { version = "0.4.38", features = ["serde"] }
anyhow = "1.0.86"
